// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsyncCom: typeof import('./src/components/AsyncComponent/AsyncCom.vue')['default']
    AsyncComError: typeof import('./src/components/AsyncComponent/AsyncComError.vue')['default']
    AsyncComponent: typeof import('./src/components/AsyncComponent/index.vue')['default']
    Child: typeof import('./src/components/ComponentVmodel/Child.vue')['default']
    ChildA: typeof import('./src/components/DynamicComponent/ChildA.vue')['default']
    ChildB: typeof import('./src/components/DynamicComponent/ChildB.vue')['default']
    ChildC: typeof import('./src/components/DynamicComponent/ChildC.vue')['default']
    ChildCom: typeof import('./src/components/ProvideInject/ChildCom.vue')['default']
    Children: typeof import('./src/components/ComponentsCommunication/children.vue')['default']
    ComponentsCommunication: typeof import('./src/components/ComponentsCommunication/index.vue')['default']
    ComponentVmodel: typeof import('./src/components/ComponentVmodel/index.vue')['default']
    DynamicComponent: typeof import('./src/components/DynamicComponent/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    EventBus: typeof import('./src/components/EventBus/index.vue')['default']
    Grandson: typeof import('./src/components/EventBus/Grandson.vue')['default']
    GrandsonA: typeof import('./src/components/ProvideInject/grandsonA.vue')['default']
    GrandsonB: typeof import('./src/components/ProvideInject/grandsonB.vue')['default']
    LeftSideMenu: typeof import('./src/components/Default/LeftSideMenu.vue')['default']
    LifeCycle: typeof import('./src/components/LifeCycle/index.vue')['default']
    ProvideInject: typeof import('./src/components/ProvideInject/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
